name: Sync to Personal Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to personal repository
        uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/${{ github.repository }}.git"
          source_branch: "main"
          destination_repo: "https://x-access-token:${{ secrets.PERSONAL_REPO_PAT }}@github.com/catmaker/kiroku-front.git"
          destination_branch: "main"
